### ISSUE TITLE
Remote Pairing Setups (Architectures) Complete with Diagrams, Requirements, Software, etc.

### ISSUE THREAD

**Issue by ChrisMcNabbSoftwareDeveloper** [avdi/ppwm#20]
I'd like to see a section of this "ppwm" repo with layout of various Remote Pair Programming Setups...including Diagrams, Requirements, Software, etc. ...with details on what's required and "how to" install and configure everything for that particular setup.  It would be simple, clean and informative.

Purpose:  The purpose of this would be when you find a remote pair partner and the two of you have now decided to pair on something, you now have to decided on HOW you are going to pair.  In other words WHAT is your setup for the actual pairing session.  If there's a place we could go to and quickly determine from the setups demonstrated on the section of this repo which setup to use, then the two pairing partners could agree on "SETUP #3", for example.  Then, each pairing partner could make sure they both are setup and configured for SETUP #3, BEFORE the pairing session starts.  Or, if they agree SETUP #5 would be easier for each of them, then they would settle on SETUP #5. They could do this initial conversation via email, or even twitter, for example.  That way, when the time comes to start paring, all the "setup/configuration/keys/etc" would have  already been done in advance and they are ready to have an effective pairing session.

For example, I started this diagram just to roll the marble around and see what popped out.  This the kind of think I'm thinking about.  This first setup could be named "Westley"...just for ease of referring to this setup by name.  (I like using the names of the characters from Princess Bride.)
![ppwm_01](https://f.cloud.github.com/assets/1703445/404079/f5544764-a936-11e2-9e44-83cca973a7b8.png)

This pairing setup is the one I've been using for the last year now and it has worked out very well!  I work from home and I pair everyday.

Notice from the picture I have sections on: tools, steps, pros, & cons.  These were just my initial thoughts.

Thoughts?  Feedback?  Hate it?  Love it? 
I'd love to hear what you have to say.
Let's all jump in and have a discussion.
Thank you!

**Comment by avdi** [comment]
Closing cuz stale
