### ISSUE TITLE
resource: slack pair app

### ISSUE THREAD

**Issue by techieshark** [avdi/ppwm#60]
Hello,

ppwm is awesome! Thanks to everyone who has been involved in getting it going.

I created a slack command that teams on slack can use to see who is interested in pairing, and on what. 

In case that is of interest to people here or for the list of resources, I thought I should share it. 

https://github.com/techieshark/slack-pair

(And of course, feedback or pairing on that app is welcome!)

**Comment by bf4** [comment]
@techieshark That's great!  You can add it on the wiki or [change this issue to a PR](http://www.databasically.com/2014/05/13/converting-a-github-issue-to-a-pull-request/) :)
